# Generated by Django 5.2.6 on 2025-09-14 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='principal',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_principal': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_of_college', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('hod', 'Head of Department'), ('principal', 'Principal'), ('superuser', 'Superuser')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.college')),
                ('hod', models.OneToOneField(blank=True, limit_choices_to={'is_hod': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of_department', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('code', 'college')},
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.department'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='core.department'),
        ),
        migrations.AlterUniqueTogether(
            name='facultyprofile',
            unique_together={('employee_id', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('student_id', 'department')},
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', 'Leave Request'), ('event', 'Event Participation'), ('project', 'Project Approval'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('supporting_documents', models.FileField(blank=True, help_text='Upload supporting documents if required', upload_to='permission_requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='core.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
