# Generated by Django 5.2.6 on 2025-09-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_college_principal_user_is_hod_user_is_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.college'),
        ),
    ]
