# Generated by Django 5.2.6 on 2025-09-16 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250915_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='designation',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='request_type',
            field=models.CharField(choices=[('leave', 'Leave'), ('on_duty', 'On Duty'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='permissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
    ]
