# Generated by Django 5.2.6 on 2025-09-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250915_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='office_location',
        ),
    ]
