# Generated by Django 5.2.6 on 2025-09-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventpermissionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('code', 'department')},
            },
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='faculty_members', to='core.subject'),
        ),
    ]
